### ISSUE TITLE
rewrite in R

### ISSUE THREAD

**Issue by MattCowgill** [MacroDave/MARTIN#1]
hi, this is really cool, it'd be better if the whole thing was rewritten in R, so please do that 

Thanks

**Comment by DavidAStephan** [comment]
I am working on a version in Python, thanks for the suggestion :-)

**Comment by MattCowgill** [comment]
Yep, I've opened an issue over there too: https://github.com/MacroDave/pyMARTIN/issues/1

**Comment by DavidAStephan** [comment]
Hi Matt, I've now got the model running in R

**Comment by MattCowgill** [comment]
👍👍👍
